AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Resources:
#=============================================
# VPC
#=============================================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: sampleVPC

#=============================================
# サブネット AZ-a
#=============================================
  Subnet01a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/20
      Tags:
      - Key: Name
        Value: public-subnet-01a

  Subnet02a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.16.0/20
      Tags:
      - Key: Name
        Value: private-subnet-02a

  Subnet03a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.32.0/20
      Tags:
      - Key: Name
        Value: private-subnet-03a

#=============================================
# サブネット AZ-c
#=============================================
  Subnet01c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.48.0/20
      Tags:
      - Key: Name
        Value: public-subnet-01c

  Subnet02c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.64.0/20
      Tags:
      - Key: Name
        Value: private-subnet-02c

  Subnet03c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.80.0/20
      Tags:
      - Key: Name
        Value: private-subnet-03c

#=============================================
# インターネットゲートウェイ
#=============================================
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: sampleIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

#=============================================
# NATゲートウェイ AZ-a
#=============================================
  NatGWa:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref Subnet01a
      AllocationId: !GetAtt EIPNatGWa.AllocationId
      Tags:
      - Key: Name
        Value: sampleNatGWa

  EIPNatGWa:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: sampleEIPNatGWa

#=============================================
# NATゲートウェイ AZ-c
#=============================================
  NatGWc:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref Subnet01c
      AllocationId: !GetAtt EIPNatGWc.AllocationId
      Tags:
      - Key: Name
        Value: sampleNatGWc

  EIPNatGWc:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: sampleEIPNatGWc

#=============================================
# ルートテーブル
#=============================================
# パブリックサブネット用
# 各AZ共通のルートテーブル
  RouteTable01:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT01

  Route01:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable01

  RouteTableAssociation01a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01a
      RouteTableId: !Ref RouteTable01

  RouteTableAssociation01c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01c
      RouteTableId: !Ref RouteTable01

# プライベートサブネット用
# AZ-a
  RouteTable02a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT02a

  Route02a:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGWa
      RouteTableId: !Ref RouteTable02a

  RouteTableAssociation02a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet02a
      RouteTableId: !Ref RouteTable02a

# AZ-c
  RouteTable02c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT02c

  Route02c:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGWc
      RouteTableId: !Ref RouteTable02c

  RouteTableAssociation02c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet02c
      RouteTableId: !Ref RouteTable02c

# プライベートサブネット用
# 各AZ共通のルートテーブル
  RouteTable03:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT03

  RouteTableAssociation03a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet03a
      RouteTableId: !Ref RouteTable03

  RouteTableAssociation03c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet03c
      RouteTableId: !Ref RouteTable03
