AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Resources:
#=============================================
# VPC
#=============================================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: sampleVPC

#=============================================
# サブネット
#=============================================
  Subnet01a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/20
      Tags:
      - Key: Name
        Value: public-subnet-01a

  Subnet02a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.16.0/20
      Tags:
      - Key: Name
        Value: private-subnet-02a

  Subnet03a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.32.0/20
      Tags:
      - Key: Name
        Value: private-subnet-03a

#=============================================
# インターネットゲートウェイ
#=============================================
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: sampleIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

#=============================================
# NATゲートウェイの作成
#=============================================
  NatGWa:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref Subnet01a
      AllocationId: !GetAtt EIPNatGWa.AllocationId
      Tags:
      - Key: Name
        Value: sampleNatGW

  EIPNatGWa:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: sampleEIPNatGWa

#=============================================
# ルートテーブル
#=============================================
  RouteTable01:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT01

  RouteTableAssociation01a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01a
      RouteTableId: !Ref RouteTable01

  Route01:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable01

  RouteTable02:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT02

  RouteTableAssociation02a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet02a
      RouteTableId: !Ref RouteTable02

  Route02a:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGWa
      RouteTableId: !Ref RouteTable02

  RouteTable03:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: sampleRT03

  RouteTableAssociation03a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet03a
      RouteTableId: !Ref RouteTable03
